# MCUboot logging
CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_INF=y


# Add DFU over UART
# CONFIG_MCUBOOT_SERIAL=y
# CONFIG_BOOT_SERIAL_UART=y
# CONFIG_UART_CONSOLE=n

# Add DFU over USB
# CONFIG_BOOT_SERIAL_CDC_ACM=y
# CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x10000

# Disable bootloader LED
CONFIG_MCUBOOT_INDICATION_LED=n
