# Copyright (c) 2023 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
CONFIG_GPIO=y
CONFIG_LED=y
CONFIG_REGULATOR=y
CONFIG_SENSOR=y
CONFIG_I2C=y

# https://docs.zephyrproject.org/latest/services/pm/index.html
# https://docs.zephyrproject.org/latest/services/pm/device.html
CONFIG_PM=y
CONFIG_PM_DEVICE=y
# CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_POWEROFF=y

# CONFIG_NRF_FUEL_GAUGE=y
CONFIG_SMF=y
CONFIG_EVENTS=y

CONFIG_LOG=y
CONFIG_CBPRINTF_FP_SUPPORT=y
# CONFIG_MAIN_STACK_SIZE=2048

# CONFIG_SHELL=y
# CONFIG_I2C_SHELL=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=n
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_PRODUCT="doorio"
CONFIG_USB_DEVICE_MANUFACTURER="denerd"
CONFIG_USB_DEVICE_PID=0x00310
CONFIG_USB_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USB_DEVICE_LOG_LEVEL_ERR=y

CONFIG_BT_DEVICE_NAME="doorio"
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
# CONFIG_BT_EXT_ADV=y

# Enable MCUMGR 
CONFIG_MCUMGR=y

# MCUMGR over Bluetooth "all in one" option
CONFIG_NCS_SAMPLE_MCUMGR_BT_OTA_DFU=y